package com.TradeTracker;

public enum MarketSector {
	
	COMMUNICATION_SEVICES,
	CONSUMER_DISCRETIONARY,
	CONSUMER_STAPLES,
	ENERGY, 
	FINANCIALS, 
	HEALTH_CARE, 
	INDUSTRIALS, 
	INFORMATION_TECHNOLOGY, 
	MATERIALS, 
	REAL_ESTATE, 
	UTILITIES;

}
